[variables]
NPM_CONFIG_PRODUCTION = 'false'
NODE_ENV = 'production'

[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = ['npm run build', 'npm prune --production']

[start]
cmd = 'npm start'
